name: mojadwel_agent
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  dart_frog: ^1.1.0
  dotenv: ^4.2.0
  firebase_admin: ^0.3.0+2
  googleapis: ^13.2.0
  googleapis_auth: ^2.0.0
  http: ^1.5.0
  meta: ^1.16.0

dev_dependencies:
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.3
  test: ^1.25.5
